NumPy
NumPy 개요 다차원 배열을 쉽게 처리하고 효율적으로 사용할 수 있도록 지원하는 파이썬 패키지 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공 데이터 분석에서 Pandas와 함께 자주 사용하는 도구

Numpy의 역할 실제로 데이터 분석을 수행하기 위한 전제조건은 컴퓨터가 이해할 수 있도록 데이터를 숫자 형식으로 변환하는 것임 파이썬의 list자료형의 경우 데이터의 크기가 커질수록 저장 및 가공에 효율성을 보장하지 못함 이러한 단점을 보완하기 위한 패키지이기 때문에 Data Science에서 핵심적인 도구로 인식되고 있음

In [3]:
import numpy as np

In [4]:
arr = np.array([1,3,5,7,9])
arr

array([1, 3, 5, 7, 9])

In [5]:
size = len(arr)
size

5

In [6]:
print(arr[0])
print(arr[1])
print(arr[2])

1
3
5


In [8]:
for i, v in enumerate(arr):
    print("%d번째 원소 >> %d" %(i, v))

0번째 원소 >> 1
1번째 원소 >> 3
2번째 원소 >> 5
3번째 원소 >> 7
4번째 원소 >> 9


In [9]:
arr3 = np.array([1,2.4,3,4.6])
arr3

array([1. , 2.4, 3. , 4.6])

In [10]:
arr4 = np.array([1.2,3,'4'])
arr4

array(['1.2', '3', '4'], dtype='<U32')

In [11]:
arr5 = np.array([1,2.4,3,4.6], dtype='int')
arr5

array([1, 2, 3, 4])

In [12]:
grade = np.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [13]:
s1 = np.sum(grade)
print("총점: %d" % s1)

총점: 338


In [14]:
s2 = np.average(grade)
print("평균 : %d" % s2)

평균 : 84


In [15]:
s3 = np.max(grade)
s4 = np.min(grade)
print("최대값 : %d, 최소값 %d" %(s3, s4))

최대값 : 91, 최소값 77


In [16]:
new1 = grade + 2
new1

array([84, 79, 93, 90])

In [17]:
new2 = grade - 5
new2

array([77, 72, 86, 83])

In [18]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [19]:
a = arr1 + arr2
a

array([12, 18, 24, 30, 36])

In [20]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [21]:
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [22]:
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

In [23]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [24]:
a = np.add(arr1, arr2)
a

array([12, 18, 24, 30, 36])

In [25]:
b = np.subtract(arr1, arr2)
b

array([ 8, 12, 16, 20, 24])

In [26]:
c = np.multiply(arr1, arr2)
c

array([ 20,  45,  80, 125, 180])

In [27]:
d = np.divide(arr1, arr2)
d

array([5., 5., 5., 5., 5.])

In [28]:
grade = np.array([82, 77, 91, 88])
grade

array([82, 77, 91, 88])

In [29]:
grade[2]

91

In [30]:
grade[1:3]

array([77, 91])

In [31]:
grade[:2]

array([82, 77])

In [32]:
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [33]:
result1 = grade[bool_array]
result1

array([82, 91])

In [34]:
result2 = grade[grade >= 80]
result2

array([82, 91, 88])

In [35]:
result3 = grade[np.logical_and(grade >= 80, grade <= 90)]
result3

array([82, 88])

In [36]:
result4 = grade[np.logical_or(grade < 80, grade > 90)]
result4

array([77, 91])

In [37]:
grade = np.array([
[98, 72, 80, 64], 
[88, 90, 80, 72], 
[92, 88, 82, 76] 
])
grade

array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82, 76]])

In [38]:
grade.ndim

2

In [39]:

grade.shape

(3, 4)

In [40]:
grade.dtype

dtype('int32')

In [41]:
grade[1,2]

80

In [42]:
grade[1:3, 1:4]

array([[90, 80, 72],
       [88, 82, 76]])

In [43]:
grade[:2, :3]

array([[98, 72, 80],
       [88, 90, 80]])

In [44]:
grade[1:, 2:]

array([[80, 72],
       [82, 76]])

In [45]:
s1 = np.sum(grade, axis=0)
print(type(s1))
s1

<class 'numpy.ndarray'>


array([278, 250, 242, 212])

In [46]:
s2 = np.sum(grade, axis=1)
type(s2)
s2

array([314, 330, 338])

In [47]:
bool_array = np.array([
[True, False, True, False],
[True, True, True, False],
[True, True, True, False]
])
result1 = grade[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

In [48]:
result2 = grade[grade >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [49]:
result4 = grade[np.logical_or(grade < 80, grade > 90)]
result4

array([98, 72, 64, 72, 92, 76])